"use client";
import Link from "next/link";
import { useEffect, useMemo, useRef, useState } from "react";
import { gsap } from "gsap";
import { BarChart3, Boxes, CheckCircle2, ChevronRight, ClipboardList, Database, FileDown, Map, Menu, Plus, Search, Building2, Monitor, Network, Landmark, X } from "lucide-react";
import { opdList, processList, rabList, ralList, services } from "@/lib/demo-data";
import type { Service } from "@/lib/types";

const nav=[ ["/layanan","Domain Proses Bisnis",ClipboardList],["/katalog","Domain Layanan",BarChart3],["/master","Domain Data",Database],["/pengajuan","Domain Aplikasi",Monitor],["/verifikasi","Domain Infrastruktur",Building2],["/gap-analysis","Aplikasi Usulan",Network],["/peta-rencana","Peta Rencana",Map],["/pengguna","Infrastruktur",Landmark] ] as const;
const badge={approved:"Disetujui",submitted:"Diajukan",draft:"Draf",rejected:"Ditolak",archived:"Arsip"} as const;
export function Portal({section}:{section:string}) { const [open,setOpen]=useState(false); const [search,setSearch]=useState(""); const [status,setStatus]=useState("all"); const [selected,setSelected]=useState<Service|null>(null); const root=useRef<HTMLDivElement>(null);
useEffect(()=>{if(root.current) gsap.fromTo(root.current.querySelectorAll(".reveal"),{y:12,opacity:0},{y:0,opacity:1,stagger:.05,duration:.42,ease:"power2.out"})},[section]);
const filtered=useMemo(()=>services.filter(s=>(status==="all"||s.status===status)&&[s.name,s.opd,s.rab].join(" ").toLowerCase().includes(search.toLowerCase())),[search,status]);
 return <div ref={root} className="min-h-screen lg:flex"><aside className={`${open?"translate-x-0":"-translate-x-full"} fixed z-30 inset-y-0 w-60 bg-white border-r border-slate-200 transition-transform lg:sticky lg:top-0 lg:h-screen lg:translate-x-0`}><div className="flex h-16 items-center gap-3 border-b px-4"><div className="grid size-9 place-items-center rounded-md border-2 border-[#ffb500] bg-white font-bold text-[#ffb500]">G</div><div><b className="block text-sm leading-tight">Kabupaten<br/>Gresik</b></div><button className="ml-auto lg:hidden" onClick={()=>setOpen(false)}><X/></button></div><nav className="p-3">{nav.map(([href,label,Icon],index)=><Link key={href} href={href} className={`mb-1 flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm ${index===0?"bg-[#ffb500] text-white":"text-slate-600 hover:bg-slate-50"}`}><Icon size={16}/>{label}</Link>)}</nav><div className="absolute bottom-10 left-4 right-4 rounded-lg border border-slate-200 bg-white p-2"><Link href="/login" className="block rounded-lg bg-[#efb400] py-2 text-center text-xs font-bold text-white">LOGIN</Link></div></aside><main className="min-w-0 flex-1"><header className="flex h-16 items-center border-b border-slate-200 bg-white px-5 lg:px-8"><button className="mr-4 lg:hidden" onClick={()=>setOpen(true)}><Menu/></button><div><p className="text-xs font-bold uppercase tracking-wider text-slate-600">Domain Arsitektur Layanan</p><h1 className="text-base font-bold">ARSITEKTUR SPBE KABUPATEN GRESIK 2025 – 2029</h1></div><div className="ml-auto rounded-lg border px-3 py-2 text-xs text-slate-600">TAHUN PERENCANAAN <b>2025–2029</b></div></header><div className="p-5 lg:p-8">{section==="Dashboard Layanan"?<Dashboard/>:section==="Input Layanan"?<ServiceForm/>:section==="Gap Analysis"?<Gap/>:section==="Peta Rencana"?<Roadmap/>:section==="Verifikasi"?<Verification/>:section==="Master Data"?<Master/>:section==="Pengguna"?<UsersPage/>:<Catalog/>}</div></main>{selected&&<Detail item={selected} onClose={()=>setSelected(null)}/>}</div>;
}
function Dashboard(){return <><Filters/><div className="reveal mt-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric title="Jumlah Layanan" value="1.284"/><Metric title="Sudah Disetujui" value="973"/><Metric title="Menunggu Validasi" value="168"/><Metric title="OPD Berpartisipasi" value="30"/></div><div className="mt-5 grid gap-5 xl:grid-cols-[1.4fr_.9fr]"><section className="card reveal p-5"><h2 className="font-bold">Referensi Arsitektur Layanan</h2><p className="mt-1 text-sm text-slate-500">Distribusi layanan menurut RAL</p><div className="mt-5 grid grid-cols-2 gap-3">{ralList.map((r,i)=><button key={r} className={`rounded-xl p-5 text-left ${i===0?"bg-[#1c73da] text-white":"bg-amber-100 text-amber-950"}`}><span className="text-xs font-bold">{r.split(" ").slice(0,2).join(" ")}</span><b className="mt-5 block text-2xl">{i?481:803}</b><span className="text-xs">layanan</span></button>)}</div></section><section className="card reveal p-5"><h2 className="font-bold">Status Pengajuan</h2><div className="mt-4 space-y-4">{[["Disetujui",76,"bg-emerald-500"],["Diajukan",13,"bg-amber-500"],["Draf",11,"bg-slate-400"]].map(([n,p,c])=><div key={String(n)}><div className="mb-1 flex justify-between text-sm"><span>{n}</span><b>{p}%</b></div><div className="h-2 rounded bg-slate-100"><div className={`h-2 rounded ${c}`} style={{width:`${p}%`}}/></div></div>)}</div></section></div><Catalog compact/></>}
function Filters(){return <div className="card reveal grid gap-3 p-4 md:grid-cols-4"><select className="field"><option>Semua OPD</option>{opdList.map(x=><option key={x}>{x}</option>)}</select><select className="field"><option>Semua status</option><option>Diajukan</option><option>Disetujui</option></select><select className="field"><option>2025–2029</option></select><select className="field"><option>Semua RAB</option>{rabList.map(x=><option key={x}>{x}</option>)}</select></div>}
function Metric({title,value}:{title:string;value:string}){return <div className="card p-5"><p className="label">{title}</p><p className="mt-2 text-3xl font-bold">{value}</p><p className="mt-1 text-xs text-emerald-600">Data periode 2025–2029</p></div>}
function Catalog({compact=false}:{compact?:boolean}){const [q,setQ]=useState("");const rows=services.filter(s=>[s.name,s.opd].join(" ").toLowerCase().includes(q.toLowerCase()));return <section className="card reveal mt-5 overflow-hidden"><div className="flex flex-wrap items-center gap-3 border-b p-4"><div><h2 className="font-bold">Katalog Layanan</h2><p className="text-xs text-slate-500">Master data arsitektur layanan</p></div><div className="relative ml-auto"><Search className="absolute left-3 top-2.5 text-slate-400" size={16}/><input className="field w-64 pl-9" value={q} onChange={e=>setQ(e.target.value)} placeholder="Cari layanan atau OPD"/></div><a href="/api/export/layanan" className="flex items-center gap-2 rounded-lg border px-3 py-2 text-sm font-semibold"><FileDown size={16}/>Export Excel</a></div><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-amber-50 text-xs uppercase text-slate-600"><tr>{["ID","Status","Layanan","Perangkat Daerah","RAL","RAB",""].map(x=><th className="px-4 py-3" key={x}>{x}</th>)}</tr></thead><tbody>{rows.slice(0,compact?4:20).map(s=><tr key={s.id} className="border-t hover:bg-slate-50"><td className="px-4 py-4 font-medium text-blue-700">{s.id}</td><td className="px-4 py-4"><Status value={s.status}/></td><td className="px-4 py-4 font-semibold">{s.name}</td><td className="px-4 py-4 text-slate-600">{s.opd}</td><td className="px-4 py-4 text-slate-600">{s.ral}</td><td className="px-4 py-4 text-slate-600">{s.rab}</td><td className="px-4 py-4"><ChevronRight size={17}/></td></tr>)}</tbody></table></div></section>}
function Status({value}:{value:Service["status"]}){return <span className={`rounded-full px-2 py-1 text-xs font-bold ${value==="approved"?"bg-emerald-100 text-emerald-700":value==="submitted"?"bg-amber-100 text-amber-700":"bg-slate-100 text-slate-600"}`}>{badge[value]}</span>}
function ServiceForm(){const [step,setStep]=useState(1);return <div className="mx-auto max-w-4xl"><div className="reveal mb-5 flex gap-2">{["Identitas","Referensi","Dampak & Risiko","Tinjau"].map((x,i)=><div key={x} className={`flex-1 rounded-lg p-3 text-center text-xs font-bold ${i+1===step?"bg-blue-600 text-white":"bg-white text-slate-400"}`}>{i+1}. {x}</div>)}</div><section className="card reveal p-6"><h2 className="text-xl font-bold">{step===1?"Identitas layanan":step===2?"Referensi arsitektur":"Informasi layanan"}</h2><div className="mt-5 grid gap-4 md:grid-cols-2"><Input label="Nama layanan" placeholder="Contoh: Layanan Informasi Publik"/><Input label="Perangkat Daerah" select values={opdList}/>{step>1&&<><Input label="RAL Level 1" select values={ralList}/><Input label="RAB Level 2" select values={rabList}/><Input label="Proses Bisnis (wajib)" select values={processList}/></>}{step>2&&<><Input label="Potensi risiko"/><Input label="Mitigasi risiko"/><Input label="Metode layanan"/><Input label="Target layanan"/></>}</div><div className="mt-7 flex justify-between"><button className="rounded-lg border px-4 py-2 text-sm" onClick={()=>setStep(Math.max(1,step-1))}>Kembali</button><button className="rounded-lg bg-blue-600 px-4 py-2 text-sm font-bold text-white" onClick={()=>setStep(step===4?4:step+1)}>{step===4?"Simpan draf":"Lanjut"}</button></div></section></div>}
function Input({label,placeholder,select,values=[]}:{label:string;placeholder?:string;select?:boolean;values?:string[]}){return <label><span className="label mb-1 block">{label}</span>{select?<select className="field"><option>Pilih {label}</option>{values.map(x=><option key={x}>{x}</option>)}</select>:<input className="field" placeholder={placeholder||`Masukkan ${label.toLowerCase()}`}/>}</label>}
function Gap(){return <div className="grid gap-5 lg:grid-cols-3">{[["Kelengkapan referensi", "23 layanan belum memiliki proses bisnis yang disetujui", "Tinggi"],["Kesesuaian RAL", "11 layanan perlu penyesuaian klasifikasi RAL", "Sedang"],["Kesiapan digital", "8 layanan memerlukan dukungan aplikasi atau infrastruktur", "Sedang"]].map(x=><section className="card reveal p-5" key={x[0]}><span className="label">{x[2]}</span><h2 className="mt-2 font-bold">{x[0]}</h2><p className="mt-3 text-sm text-slate-600">{x[1]}</p><button className="mt-5 text-sm font-bold text-blue-700">Buat usulan peta rencana</button></section>)}</div>}
function Roadmap(){return <section className="card reveal overflow-hidden"><div className="border-b p-5"><h2 className="font-bold">Peta Rencana 2025–2029</h2><p className="text-sm text-slate-500">Usulan yang dihasilkan dari Gap Analysis</p></div>{[["2025","Standardisasi master Proses Bisnis","selesai"],["2026","Integrasi layanan dan aplikasi","berjalan"],["2027","Penguatan keamanan layanan","belum mulai"],["2028","Evaluasi dan penyempurnaan","belum mulai"],["2029","Konsolidasi arsitektur","belum mulai"]].map(([year,name,status])=><div className="flex gap-4 border-b p-5" key={year}><div className="grid size-12 shrink-0 place-items-center rounded-full bg-blue-50 font-bold text-blue-700">{year}</div><div><b>{name}</b><p className="mt-1 text-sm text-slate-500">Target, evaluasi, dan tindak lanjut dapat dikelola per tahun.</p></div><span className="ml-auto text-xs font-bold text-slate-500">{status}</span></div>)}</section>}
function Verification(){return <section className="card reveal p-6"><h2 className="font-bold">Antrean verifikasi Bagian Organisasi</h2><p className="mt-1 text-sm text-slate-500">Setujui atau kembalikan usulan dengan catatan evaluasi.</p><div className="mt-5 space-y-3">{services.filter(s=>s.status==="submitted").map(s=><div key={s.id} className="rounded-xl border p-4"><b>{s.name}</b><p className="mt-1 text-sm text-slate-500">{s.opd} · {s.processBusiness}</p><div className="mt-3 flex gap-2"><button className="rounded-lg bg-emerald-600 px-3 py-2 text-xs font-bold text-white">Setujui</button><button className="rounded-lg border px-3 py-2 text-xs font-bold">Kembalikan</button></div></div>)}</div></section>}
function Master(){return <div className="grid gap-4 md:grid-cols-3">{[["RAL",ralList.length],["RAB",rabList.length],["Proses Bisnis",processList.length]].map(x=><div className="card reveal p-5" key={String(x[0])}><p className="label">Master {x[0]}</p><p className="mt-2 text-3xl font-bold">{x[1]}</p><button className="mt-4 text-sm font-bold text-blue-700">Kelola data</button></div>)}</div>}
function UsersPage(){return <section className="card reveal p-6"><h2 className="font-bold">Pengelolaan pengguna</h2><p className="mt-1 text-sm text-slate-500">Superadmin mengelola akun dan peran lokal.</p><div className="mt-5 rounded-lg bg-slate-50 p-4 text-sm"><b>Admin Diskominfo</b><br/><span className="text-slate-500">superadmin · admin@gresikkab.go.id</span></div></section>}
function Detail({item,onClose}:{item:Service;onClose:()=>void}){return <div className="fixed inset-0 z-40 grid place-items-center bg-slate-900/40 p-4"><section className="card w-full max-w-2xl p-6"><div className="flex"><div><p className="label">{item.id}</p><h2 className="mt-1 text-xl font-bold">{item.name}</h2></div><button className="ml-auto" onClick={onClose}><X/></button></div><div className="mt-6 grid gap-4 sm:grid-cols-2">{[["OPD",item.opd],["Status",badge[item.status]],["Tujuan",item.purpose],["Fungsi",item.function],["Proses Bisnis",item.processBusiness],["Risiko",item.risk]].map(x=><div key={x[0]}><p className="label">{x[0]}</p><p className="mt-1 text-sm">{x[1]}</p></div>)}</div></section></div>}
