"use client";
import Link from "next/link";
import { Building2, Database, Eye, Landmark, LayoutGrid, Map, Monitor, Network, Search, X } from "lucide-react";
import { opdList, rabList, services } from "@/lib/demo-data";
import type { Service } from "@/lib/types";
import { useState } from "react";

const nav=[["Domain Proses Bisnis",LayoutGrid],["Domain Layanan",Building2],["Domain Data",Database],["Domain Aplikasi",Monitor],["Domain Infrastruktur",Landmark],["Aplikasi Usulan",Network],["Peta Rencana",Map],["Infrastruktur",Building2]] as const;
export function PublicDashboard(){return <div className="min-h-screen bg-[#f2f4f7] lg:flex"><aside className="hidden h-screen w-60 shrink-0 border-r border-slate-200 bg-white lg:sticky lg:top-0 lg:block"><div className="flex h-20 items-center gap-3 border-b px-5"><div className="grid size-11 place-items-center rounded-full border-2 border-[#efb400] font-bold text-[#efb400]">G</div><b className="text-sm leading-tight">Kabupaten<br/>Gresik</b></div><nav className="p-4">{nav.map(([label,Icon],i)=><div className={`mb-1 flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm ${i===0?"bg-[#ffb500] text-white":"text-slate-600"}`} key={label}><Icon size={16}/>{label}</div>)}</nav><div className="absolute bottom-10 left-4 right-4 rounded-xl border border-slate-200 p-2.5"><Link className="block rounded-lg bg-[#efb400] py-2 text-center text-xs font-bold text-white" href="/login">LOGIN</Link></div></aside><main className="min-w-0 flex-1"><header className="flex h-16 items-center border-b bg-white px-6"><div><p className="text-[10px] font-bold uppercase tracking-wider text-slate-500">Domain Proses Bisnis</p><h1 className="text-sm font-bold">ARSITEKTUR SPBE KABUPATEN GRESIK 2025 – 2029</h1></div><span className="ml-auto rounded-lg border px-3 py-2 text-xs">TAHUN PERENCANAAN&nbsp; <b>2025–2029</b></span></header><div className="p-5 lg:p-8"><div className="grid gap-3 rounded-lg border bg-white p-3 md:grid-cols-3"><Select label="Status"/><Select label="Sasaran"/><Select label="RAB Level 3"/></div><section className="mt-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Jumlah Proses Bisnis" value="1.845"/><Metric label="Probis AS-IS" value="1.513"/><Metric label="Probis Upgrade" value="143"/><Metric label="Probis New" value="189"/></section><section className="mt-5 grid gap-5 xl:grid-cols-[1.2fr_1.2fr_.9fr]"><Reference/><Heatmap/><OpdSummary/></section><Catalog/></div></main></div>}
function Select({label}:{label:string}){return <label className="flex rounded-lg bg-[#f8fafc] px-3 py-2 text-xs text-slate-500"><span>{label}</span><select className="ml-3 flex-1 bg-transparent text-slate-700 outline-none"><option>Semua</option></select></label>}
function Metric({label,value}:{label:string;value:string}){return <div className="card bg-[#fffdf7] p-4"><p className="label">{label}</p><b className="mt-2 block text-2xl">{value}</b></div>}
function Reference(){return <section className="card p-4"><h2 className="border-l-2 border-[#ff9f00] pl-2 text-sm font-bold">Referensi Arsitektur Proses Bisnis (RAB)</h2><p className="mt-3 text-xs font-bold">Heat Map Arsitektur Level 1 (Sektor)</p><div className="mt-2 grid grid-cols-2 gap-2"><Tile text="RAB.02 Ekonomi dan Industri" n="2.316" strong/><Tile text="RAB.09 Pemerintahan Umum" n="187"/><Tile text="RAB.03 Pembangunan dan Kewilayahan" n="238"/><Tile text="RAB.06 Sosial" n="94"/></div></section>}
function Tile({text,n,strong}:{text:string;n:string;strong?:boolean}){return <div className={`rounded-lg p-3 text-center text-[10px] ${strong?"bg-[#f28b00] text-white":"bg-[#ffe68b]"}`}><b className="block">{text}</b><span>({n})</span></div>}
function Heatmap(){return <section className="card p-4"><p className="border-l-2 border-[#ff9f00] pl-2 text-sm font-bold">RAB Level 2 (Urusan)</p><div className="mt-3 grid grid-cols-3 gap-2">{rabList.concat(["RAB.04 Pemerintahan","RAB.06 Sosial","RAB.09 Lainnya"]).map((x,i)=><Tile key={x} text={x} n={String(64-i*5)}/>)}</div></section>}
function OpdSummary(){return <section className="card p-4"><h2 className="border-l-2 border-[#ff9f00] pl-2 text-sm font-bold">Perangkat Daerah pemilik Proses Bisnis</h2><table className="mt-3 w-full text-xs"><thead className="text-slate-400"><tr><th className="text-left">NO.</th><th className="text-left">PERANGKAT DAERAH</th><th>JUMLAH</th></tr></thead><tbody>{opdList.slice(0,5).map((o,i)=><tr className="border-b" key={o}><td className="py-2">{i+1}</td><td>{o}</td><td className="text-right">{153-i*18}</td></tr>)}</tbody></table><p className="mt-3 text-xs font-bold">Total Perangkat Daerah <span className="float-right">30</span></p></section>}
function Catalog(){const [selected,setSelected]=useState<Service|null>(null);return <><section className="card mt-5 overflow-hidden"><div className="flex flex-wrap items-center gap-3 border-b p-4"><h2 className="border-l-2 border-[#ff9f00] pl-2 text-sm font-bold">Katalog Proses Bisnis Perangkat Daerah</h2><div className="ml-auto flex items-center gap-2 rounded-lg border px-3 py-2 text-xs text-slate-500"><Search size={14}/>Cari proses bisnis, perangkat daerah</div><span className="rounded-lg border px-3 py-2 text-xs">Tampilkan Kolom</span></div><div className="overflow-x-auto"><table className="w-full min-w-[980px] text-left text-sm"><thead className="bg-[#fff9e8] text-[10px] uppercase text-slate-600"><tr>{["ID","Status","Proses Bisnis","Perangkat Daerah","Tujuan Strategis","IKU","RAB","Aksi"].map(x=><th className="p-3" key={x}>{x}</th>)}</tr></thead><tbody>{services.map(s=><tr className="border-t border-slate-100" key={s.id}><td className="p-3 text-xs">PRB-{s.id.slice(-3)}</td><td className="p-3"><span className="rounded bg-amber-100 px-2 py-1 text-[10px]">Upgrade</span></td><td className="p-3 text-xs font-semibold">{s.processBusiness}</td><td className="p-3 text-xs">{s.opd}</td><td className="p-3 text-xs">{s.purpose}</td><td className="p-3 text-xs">Indeks SPBE</td><td className="p-3 text-xs">{s.rab}</td><td className="p-3"><button onClick={()=>setSelected(s)} aria-label="Lihat detail"><Eye size={15}/></button></td></tr>)}</tbody></table></div></section>{selected&&<Detail item={selected} close={()=>setSelected(null)}/>}</>}
function Detail({item,close}:{item:Service;close:()=>void}){return <div className="fixed inset-0 z-50 grid place-items-center bg-[#071324]/75 p-3"><section className="w-full max-w-[840px] overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-2xl"><header className="flex items-start border-b border-slate-100 px-6 py-5"><div className="mr-3 grid size-9 place-items-center rounded-lg bg-[#fff4dc] text-[#ef9700]">▣</div><div><h2 className="text-sm font-bold">Detail Proses Bisnis</h2><p className="mt-1 text-[10px] text-slate-400">Informasi lengkap arsitektur proses bisnis Pemerintah Kabupaten Gresik</p></div><button onClick={close} className="ml-auto text-slate-400"><X size={16}/></button></header><div className="space-y-4 px-6 py-4"><div className="flex flex-wrap gap-2 text-[9px]"><span className="rounded-md bg-slate-100 px-2.5 py-1 font-bold">Kode: {item.id}</span><span className="rounded-md bg-[#fff0c7] px-2.5 py-1 font-bold text-[#a46300]">● Status: Upgrade</span><span className="rounded-md bg-[#dff8e7] px-2.5 py-1 font-bold text-[#168149]">♙ {item.opd}</span><span className="ml-auto rounded-md bg-slate-100 px-2.5 py-1">▣ Tahun: 2025 – 2029</span></div><section className="rounded-xl border border-[#ffe3a5] bg-[#fffdf8] p-4"><p className="text-[9px] font-bold uppercase text-[#ee9500]">Nama & Uraian Bisnis Proses</p><h3 className="mt-1 text-xs font-bold">{item.processBusiness}</h3><p className="mt-3 rounded-lg border border-slate-100 bg-white p-3 text-[10px] leading-relaxed text-slate-500">{item.purpose}. Proses bisnis ini mencakup tahapan penyusunan, harmonisasi, pelaksanaan standar operasional, dan pemantauan layanan Pemerintah Kabupaten Gresik.</p></section><section className="rounded-xl border border-slate-100 p-4"><p className="text-[9px] font-bold uppercase text-[#ee9500]">Klasifikasi Referensi Arsitektur Bisnis (RAB)</p><div className="mt-3 grid gap-2 sm:grid-cols-3"><Box label="RAB Level 1" value="RAB.09 Pemerintahan Umum"/><Box label="RAB Level 2" value={item.rab}/><Box label="RAB Level 3" value="Penataan Sumber Daya Manusia Aparatur"/></div></section><div className="grid gap-3 sm:grid-cols-2"><Box label="Tujuan Strategis" value={item.purpose}/><Box label="Indikator Kinerja Utama (IKU)" value="Indeks Sistem Merit    Sangat Baik"/></div></div><footer className="flex items-center border-t border-slate-100 px-6 py-4"><p className="text-[9px] text-slate-400">Katalog Arsitektur SPBE · Pemerintah Kabupaten Gresik</p><button onClick={close} className="ml-auto rounded-lg bg-[#ff9f00] px-6 py-2 text-xs font-bold text-white">Tutup</button></footer></section></div>}
function Box({label,value}:{label:string;value:string}){return <div className="rounded-lg bg-slate-50 p-3"><p className="label">{label}</p><p className="mt-1 text-xs font-semibold">{value}</p></div>}
